/**
 * Constants for the application
 */

const urls = {
    GET: 'GET',
    POST: 'POST',

}

const screenNames = {
    // Common screens
    SPLASH_SCREEN: "SPLASH_SCREEN",
    AUTH_STACK: "AUTH_STACK",
    APP_STACK: "APP_STACK",

    // AUTH SCREENS
    LOGIN_SCREEN: "LOGIN_SCREEN",
    FORGOT_PASSWORD_SCREEN: "FORGOT_PASSWORD_SCREEN",
    ENTER_OTP_SCREEN: "ENTER_OTP_SCREEN",
    RESET_PASSWORD_SCREEN: "RESET_PASSWORD_SCREEN",
    SIGN_UP_SCREEN: "SIGN_UP_SCREEN",

    // TABS SCREEN
    HOME_TAB_SCREEN: "HOME_TAB_SCREEN",
    HISTORY_TAB_SCREEN: "HISTORY_TAB_SCREEN",
    PROFILE_TAB_SCREEN: "PROFILE_TAB_SCREEN",

    // STACK SCREENS
    HOME_SCREEN: "HOME_SCREEN",
    HISTORY_SCREEN: "HISTORY_SCREEN",
    PROFILE_SCREEN: "PROFILE_SCREEN",
    CREATE_REQUEST_SCREEN: "CREATE_REQUEST_SCREEN",
    CONFIRM_REQUEST_SCREEN: "CONFIRM_REQUEST_SCREEN",
    REQUEST_DETAIL_SCREEN: "REQUEST_DETAIL_SCREEN",
    PAYMENT_HISTORY_SCREEN: "PAYMENT_HISTORY_SCREEN",
    SETTING_SCREEN: "SETTING_SCREEN",
    SUPPORT_SCREEN: 'SUPPORT_SCREEN',
    INVITE_SCREEN: 'INVITE_SCREEN'
}

const itemTypes = {
    BAGS: 1,
    CHILD_EQUIPMENT: 2,
    OVER_SIZE_ITEMS: 3,
}

const RequestStatus = {
    PENDING: 1,
    APPROVED: 2,
    REJECTED: 3,
    CANCELLED: 4,
    ACTION_PERFORMED: 5, // Not a status but adding to avoid hard coded checks
}

const statsTypes = {
    ACTION_CLICK: 1,
    EVENT_CLICK: 2,
    HOT_DEAL_CLICK: 3,
    CLICK_ON_CALL: 4,
    REDIRECT_TO_WEBSITE: 5,
    PROFILE_VISITED: 6,
    DEALS_SAVED_BOOKED: 7,
    NEW_CHAT_INITIATED: 8,
    SAVED_AS_FAVORITE: 9,
    TOTAL_REQUESTS: 10,
    REQUESTS_ACCEPTED: 11,
    REQUESTS_REJECTED: 12,
    REQUESTS_NOT_ANSWERED: 13,
    DEALS_REDEEMED: 14,
    CLICK_ON_INFO: 15,
    REDIRECT_TO_GOOGLE_MAP: 16,
    MESSENGER_CLICK: 26,
}

const notificationTypes = {
    MESSAGE: 1,
    FOR_PRODUCT: 2,
    FROM_SUPER_ADMIN: 3,
    MARK_ENT_FAV: 4,
    APPOINTMENT: 5,
}

const constants = {
    SPLASH_WAIT_TIME: 3000,
    BACK_WAIT_TIME: 3000,
    HANDLING_TIMEOUT: 500,
    PAGE_SIZE: 10,
    MIN_HEIGHT_FOR_FLAT_LIST: 180,
    CARD_UPPER_VIEW_HEIGHT_PERCENTAGE: 14.5,
    BIG_CARD_UPPER_HEIGHT_PERCENTAGE: 16,
    ADS_INTERVAL: 4000,
    LOGO_VIEW_HEIGHT_PERCENTAGE: 0.10,
    HEADER_IMAGE_HEIGHT_PERCENTAGE: 0.5234,
    MESSENGER_LISTING_REFRESH_INTERVAL: 5000,
    MESSAGE_REFRESH_INTERVAL: 5000,
    SAVED_DEAL_TIMER_INTERVAL: 1000,
    SHORT_DESCRIPTION_TRIM: 20,
    ANDROID: "android",
    IOS: "ios",
    TYPE_OF_USER: "TYPE_OF_USER",
    AUTH_TOKEN: "AUTH_TOKEN",
    GUEST_AUTH_TOKEN: "guestlogin",
    IS_USER_LOGGED_IN: "IS_USER_LOGGED_IN",
    LOGGED_IN_USER: "LOGGED_IN_USER",
    APPLE_USER: "APPLE_USER",
    EMAIL_REGULAR_EXPRESSION: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
    MOBILE_REGULAR_EXPRESSION: /^\d+$/,
    COORDINATES: "COORDINATES",
    SELECTED_LANGUAGE: "SELECTED_LANGUAGE",
    CURRENT_SELECTED_LANGUAGE: "",
    CURRENT_COUNT_FOR_FAILURE: 5,
    EXTENSION_MINUTES: 30,
    APPOINTMENT_EXTENSION_MINUTES: 60,
    REDEEM_END_EXTENSION_MINUTES: 180,
    DISTANCE_FOR_CHECK_IN: 100, // meters
    EXTRA_DAYS_FOR_APPOINTMENTS: 180, // days
    INTERVAL_FOR_APPOINTMENTS: 5, // minutes
    CONTACT_US_EMAIL_ID: "contactus@blocally.de",
    CHAR_MAX_LIMIT: 20,
    CONTACT_NAME_LIMIT: 50,
    EMAIL_CHAR_MAX_LIMIT: 50,
    PHONE_CHAR_MAX_LIMIT: 15,
    PHONE_CHAR_MIN_LIMIT: 7, // if changing, then change in strings.js also mobile_should_be
    ADDRESS_CHAR_MAX_LIMIT: 100,
    NUM_OF_GUESTS_MAX_LIMIT: 3,
    NUM_OF_MAX_DEALS_LIMIT: 4,
    MAX_NUM_OF_DEAL: 1000,
    APPOINTMENT_NOTE_MAX_LIMIT: 200,
    OTP_CHAR_MAX_LIMIT: 4,
    // FCM
    FCM_TOKEN: "FCM_TOKEN",
    FCM_CHANNEL_ID: "BLocally-Channel",
    FCM_CHANNEL_NAME: "General",
    FCM_CHANNEL_DESCRIPTION: "Notifications regarding deals",
    FCM_GROUP_NOTIFICATION_ID: "BLocally-Group-Notification",
    FCM_GROUP_ID: "BLocally-Group",
    FCM_GROUP_NAME: "General",
    FCM_TAG: "BLocally-Tag",
    IS_CHAT_SCREEN: false,
    CURRENT_CHAT_ENT_ID: -1,

    SHOULD_SHOW_TIME_POPUP: "SHOULD_SHOW_TIME_POPUP",

    // API Response codes
    INVALID_AUTH_TOKEN_CODE: 102,
    PRODUCT_UNPUBLISHED: 135,
    ADD_APPOINTMENT_LIMIT_REACHED: 137,
}

const languages = {
    english: "en",
}

export {
    urls,
    screenNames,
    constants,
    itemTypes,
    languages,
    RequestStatus,
    statsTypes,
    notificationTypes
}